# Generated by Django 5.0 on 2024-08-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.IntegerField()),
                ('st_name', models.CharField(max_length=50)),
                ('st_email', models.EmailField(max_length=50)),
                ('st_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
